name: Geode

on:
  push:
    branches:
      - main
  workflow_dispatch: # This enables manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Geode mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: 'latest'
          cli: 'latest'
          configure-args: ''
          build-args: ''
          build-config: 'release'
          export-pdb: ''
          path: ''
          combine: 'false'
          target: 'Win64'
          bindings: ''
          bindings-ref: ''
          android-min-sdk: ''
          use-lto: 'true'
